### PR TITLE
First draft of leader election details.

### PR DESCRIPTION
**Pull request by happi**
Please comment on the whole approach as well as all the names:
MINIMUM_STAKE
register
top_up
withdraw
tokens_at_stake

(Sorry, I also did some general cleanup. New stuff lines 509-538)

### CODE REVIEW

**Comment by ThomasArts** [comment]
I see an unsolved issue with extracting stake directly after leader elects the schedule.
At the start of an epoch we decide the schedule of the complete epoch based on the stake. If that schedule is set, the stakeholders could in principle walk away with the stake.
Do we allow this or are there measures in place to somehow block the stake during the epoch?

**Comment by happi** [comment]
> I see an unsolved issue with extracting stake directly after leader elects the schedule. At the start of an epoch we decide the schedule of the complete epoch based on the stake. If that schedule is set, the stakeholders could in principle walk away with the stake. Do we allow this or are there measures in place to somehow block the stake during the epoch?

Blocks should only be accepted if the stake is still there in the staking contract. Not only at the beginning of the epoch.

I thought this was clear enough:
> During the block production epoch, blocks are considered valid only if they are produced by validators who have at least the `tokens_at_stake` in (their deposit in the election contract + their token balance in the staking contract).

But clarifications are welcome.

**Comment by happi** [comment]
The MINIMUM_STAKE should "be at stake" you should not be allowed to withdraw that if your tokens_at_stake is > 0.
But I think it is ok to walk away with the other stake (at least in version 1.0) but then you can not validate.

**Comment by hanssv** [comment]
Looks solid to me, perhaps `deposit` instead of `top_up`?

**Pull request merged**
